### ISSUE TITLE
[Bug] Dice do not function at all when used. v1.1.17

### ISSUE THREAD

**Issue by Sourceshard** [Theronguard/Emergency-Dice#13]
Dice when used do nothing. They sit and spin on the ground. Errors are generated in the log. V1.1.18 was not available for me to test. Not sure it this was fixed. In case it is not here is the log.

[message (11).txt](https://github.com/Theronguard/Emergency-Dice/files/14898281/message.11.txt)

**Comment by Theronguard** [comment]
I noticed that when I was testing the mod in isolation, it worked. But as soon as i played with other mods it broke, so there's maybe a conflict going on. I don't have that much time lately, but i'll try to look into it when I can.

**Comment by Theronguard** [comment]
Okay, I looked into it and I think I get why this happens. I couldn't replicate the problem on my side sadly. Tried with mods, tried with no mods. All was well. According to @Sourceshard log, the dice stops working right before causing the effect. That's because the dice has to drop, spin, explode and then causes the effect. Seems like the explosion is broken: **"MissingMethodException: Method not found: void .Landmine.SpawnExplosion"** and this stops the effect from happening. This is a LethalCompany method, so it can't be missing unless it was removed or modified (but it wasn't).

This probably happens due to old lethal company assemblies on which my mod depends on. In the last version (1.1.18) i recompiled the assemblies for the **V50 public test** version, so if you want to play this mod you need V50, and make sure to update **LethalLib**. If you really need V49 to work then I could compile my mod for it, but I'd have to put it on github and you'd have to install it manually as I don't want it to overwrite the latest version.

Please let me know if the newest version works, If it doesn't, post the error log, as there might be more to this problem.

I recompiled everything and again uploaded it to thunderstore with updated dependency strings, so it might take 30-60 minutes to appear. Make sure you use 1.1.18 (or later). You can also try to remove the mod's config file and let it regenerate if the update doesn't help.

**Comment by Nemesis041** [comment]
Are there any new changes or other fixes between 1.1.16 to 1.1.19? Currently playing V49 with 1.1.16 with no issues and not updating because when I tried it, the dice when I tried to roll them just stayed on the ground as if I normally dropped them, but they simply could not be picked back up, so I simply reverted back to 1.1.16.

Just asking if I'm missing anything significant is all. I cannot find any patch notes here for the life of me for whatever reason.

**Comment by Sourceshard** [comment]
https://github.com/Theronguard/Emergency-Dice/issues/13#issuecomment-2053607873

Any way to add in compatibility for v49 where on startup it looks for the v49 Method first, and failing to find it, it then looks for the v50 method? Then the mod adapts to use the correct method based on the version.

Currently, I have been using v1.1.16 and sometimes the dice disappear.  I would like to use this mod for my v49 mod pack in its most stable condition.


Also, I have no idea where your changelogs are on your Github. Is there any way you could still maintain the changelog.md? It is much easier for those using your mod.

**Comment by PrimoDev23** [comment]
Since these methods are used during compile time I think it is unlikely that there is a way to get this working for multiple versions. Though I haven't ever developed a mod for LC on my own, so others probably will know better.
I compiled the 1.1.19 (v49) for me and my friends so we can use this mod. If the developer is fine with it I can send the zip here and you can import it into LC.

Keep in mind I just quickly tested this on a single player save, but everything worked just fine for me.

**Comment by PrimoDev23** [comment]
Also to the dev... I have just found some other mod ensuring compatibility with older game versions like this https://github.com/Malcolm-Q/LC-LateGameUpgrades/blob/196386062e388dc3c9d395392ddabf88a4099ad0/MoreShipUpgrades/Misc/Util/Tools.cs#L260

You might wanna consider doing the same, so you can satisfy everyone 😄

**Comment by Theronguard** [comment]
I updated the mod to 1.1.20. Hopefully the #15 merge fixed it! 

Also if you want to see the changelog, you can check commits. I didn't think it through and most of the commits aren't versioned (but the version can be checked in the commit's MysteryDice.cs file at the top). I will try to remember to put them there. Sorry for the inconvinience. It's just less of a hassle for me to write every change in the commit log.

**Comment by Sourceshard** [comment]
just in time fo v50 to drop haha

**Comment by Theronguard** [comment]
I wasn't aware of this at first because I'm new to modding unity games, but when an assembly I referenced changes, the methods I use from it won't work.  That's why when I updated the mod with the new V50 .dll files, the V49 broke. Last version that seemed to work okay for V49 was **1.1.16** which you can download on Thunderstore. I won't be providing new updates for V49, only for the newest versions.
